package com.galapass.api.entity.tour;

public enum TourTag {
    FAMILY_FRIENDLY,
    LUXURY,
    BUDGET,
    FULL_DAY,
    HALF_DAY,
    MULTI_DAY,
    PRIVATE,
    GROUP,
    ACCESSIBLE,
    ECO_FRIENDLY,
    ISLAND_HOPPING,
    BEACH,
    SUNSET,
    WILDLIFE_FOCUS,
    MARINE_FOCUS,
    LAND_FOCUS,
    BEGINNER_FRIENDLY,
    ADVANCED,
    PHOTOGRAPHY_OPPORTUNITY
}
